### ISSUE TITLE
Disable crafting does not work like it should

### ISSUE THREAD

**Issue by johnfriedrich** [Monospark/ActionControl#1]
Hi,
I am trying to block crafting of some Pixelmon items.

I tried this:
craft {
        filter {
            # Crafting ThunderstonePickaxe
            result = "{'type': 'pixelmon:ThunderstonePickaxe'}"
        },
        response {
            match = "deny"
        }

I can't take the item with a leftclick, but with a rightclick. Any way to block this too?

**Comment by Milchshakee** [comment]
I'm sorry for answering late, but somehow my GitHub notifications settings were messed up and I didn't recieve this message.

It seems like I forgot about the right click, I will quickly add this.

**Comment by Milchshakee** [comment]
Should be fixed now.
You can download the new version only on GitHub since Ore currently doesn't let me upload files for whatever reason.

**Comment by johnfriedrich** [comment]
Thank you!
